apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccds-test-deployment
  namespace: ccds-test-namespace
  labels:
    app: ccds-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccds-test-app
  template:
    metadata:
      labels:
        app: ccds-test-app
    spec:
      containers:
      - name: ccds-dummy-container
        image: mkubica/ccds-dummy-container:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always