apiVersion: v1
kind: Service
metadata:
  name: ccds-test-service
  namespace: ccds-test-namespace
  labels:
    app: ccds-test-app
spec:
  type: LoadBalancer
  selector:
    app: ccds-test-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80